left_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver: baxter_left_arm_kinematics/IKFastKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
right_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver: baxter_right_arm_kinematics/IKFastKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
